export type BrowserPage =
  | 'home'
  | 'news'
  | 'weather'
  | 'stocks'
  | 'sports'
  | 'history'
  | 'search'
  | 'winrarDownload'
  | 'portalResetPassword';

export const embarrassingHistoryEntries = [
  '2:11 PM - "how do i get my ex back fast"',
  '2:10 PM - "how to seem unbothered but actually bothered"',
  '2:09 PM - "how to get a six pack in 1 week no exercise"',
  '2:08 PM - "can confidence be purchased online"',
  '2:07 PM - "apology text templates that sound accidental"',
  '2:06 PM - "best revenge glow up timeline realistic"',
  '2:05 PM - "can i become mysterious by wearing black turtlenecks"',
  '2:04 PM - "how to look busy when boss walks by"',
  '2:03 PM - "is soup a beverage legal definition"',
  '2:02 PM - "cheap abs in 7 days guaranteed"',
  '2:01 PM - "how to unsend a message from 2004"',
  '2:00 PM - "does my plant think im dramatic"',
  '1:59 PM - "how to accidentally post gym selfie"',
  '1:58 PM - "can i put confidence on my resume"',
  '1:57 PM - "haircut that says i read books"',
  '1:56 PM - "how to apologize but still win argument"',
  '1:55 PM - "why did i wave at someone i dont know"',
  '1:54 PM - "is 3 coffees breakfast"',
  '1:53 PM - "how long can i fake liking jazz"',
  '1:52 PM - "how to stop typing lol in serious emails"',
  '1:51 PM - "can i become left handed for aesthetic"',
  '1:50 PM - "how to look rich in grocery store"',
  '1:49 PM - "do sunglasses hide panic"',
  '1:48 PM - "how to delete memory of karaoke"',
  '1:47 PM - "best excuses for owning 14 throw pillows"',
  '1:46 PM - "can i gain muscle by thinking hard"',
  '1:45 PM - "what is business casual for emotional support hoodie"',
  '1:44 PM - "how to text hey without seeming desperate"',
  '1:43 PM - "is it illegal to overuse ellipses..."',
  '1:42 PM - "how to recover from saying you too to waiter"',
  '1:41 PM - "how to politely reject pyramid scheme aunt"',
  '1:40 PM - "do i need protein shake to open jars"',
  '1:39 PM - "is 11 alarms a personality trait"',
  '1:38 PM - "how to stop buying self help books i dont read"',
  '1:37 PM - "quickest path to mysterious villain energy"',
  '1:36 PM - "can i list vibes as a skill"',
  '1:35 PM - "how to ask for raise using interpretive dance"',
  '1:34 PM - "why did i say love you on customer support call"',
  '1:33 PM - "can mirrors be gaslighting me"',
  '1:32 PM - "how to become morning person by friday"',
  '1:31 PM - "how to remove glitter from car seats permanently"',
  '1:30 PM - "best fake hobbies for first dates"',
  '1:29 PM - "is 2am cereal dinner acceptable"',
  '1:28 PM - "how to train jawline while watching tv"',
  '1:27 PM - "can i reset my reputation in new zip code"',
  '1:26 PM - "why does my voice crack when ordering coffee"',
  '1:25 PM - "how to wear chain without becoming magician"',
  '1:24 PM - "can i get six pack from laughing hard"',
  '1:23 PM - "how to recover from seen at 1:23 PM"',
  '1:22 PM - "is confidence just good posture"',
  '1:21 PM - "how to stop saying no worries when there are worries"',
  '1:20 PM - "how to win argument with autocorrect"',
  '1:19 PM - "is soup still beverage if chunky"',
  '1:18 PM - "how to make playlist that implies emotional stability"',
  '1:17 PM - "how to tell barber just a little off means little"',
  '1:16 PM - "can i meal prep charisma"',
  '1:15 PM - "how to look athletic in elevator"',
  '1:14 PM - "how to flirt without sounding like a chatbot"',
  '1:13 PM - "can i invoice my ex for emotional labor"',
  '1:12 PM - "best way to return to gym after 4 years"',
  '1:11 PM - "how to become hot by next tuesday"',
] as const;
