export const iconIds = [
  'accessibility',
  'addConnection',
  'addHardware',
  'addPrinter',
  'addRemovePrograms',
  'binEmpty',
  'binFull',
  'blackjack',
  'bmpFile',
  'briefcase',
  'cdDrive',
  'cdTrack',
  'controlPanel',
  'dateTime',
  'clock1',
  'cleanDrive1',
  'dialUpNetwork',
  'display',
  'documents',
  'error',
  'msgError0',
  'globe',
  'gameFreecell2',
  'gameSpider0',
  'hardDrive',
  'helpFile',
  'exchange',
  'explorer',
  'floppyDrive',
  'folderOpen',
  'folderClosed',
  'fallback',
  'fonts',
  'fontsShortcut',
  'fontFile',
  'fontTtFile',
  'help',
  'internet',
  'joystick',
  'keyboard',
  'leaderboard',
  'menuArrow',
  'midiFile',
  'minesweeper',
  'modems',
  'mouse',
  'msFax',
  'msMail',
  'mailEnvelope',
  'envelopeClosed0',
  'mailEnvelopeOpen',
  'earthRating',
  'mailFolderClosed',
  'mailFolderOpen',
  'mailSent',
  'mailSpam',
  'mailToolDelete',
  'mailToolForward',
  'mailToolNew',
  'mailToolReply',
  'mailToolSend',
  'mailTrashEmpty',
  'mailboxWorld0',
  'microsoftMoney99',
  'multimedia',
  'music',
  'network',
  'networkNeighborhood',
  'netVoiceHandset',
  'notepad',
  'notepadDoc',
  'passwords',
  'passwordVault',
  'power',
  'printers',
  'printersShortcut',
  'program',
  'programs',
  'quickView',
  'regionalSettings',
  'question',
  'restrict1',
  'settings',
  'shutdown',
  'smiley',
  'sound',
  'sounds',
  'soundOff',
  'system',
  'tree',
  'trust00',
  'ultimateCasino',
  'video',
  'videoFile',
  'volume',
  'warning',
  'waveFile',
  'windowsLogo',
  'webFileSet0',
  'winRar3',
  'lotusWordPro97',
  'wordpadDoc',
] as const;

export type IconId = typeof iconIds[number];

export const iconSizes = [8, 16, 24, 32] as const;

export type IconSize = typeof iconSizes[number];

export type IconUrls = Partial<{ [key in IconSize]: string }>;

export type IconList = { [key in IconId]: IconUrls };
