export const iconIds = [
  'binEmpty',
  'blackjack',
  'bmpFile',
  'briefcase',
  'cdTrack',
  'controlPanel',
  'clock1',
  'cleanDrive1',
  'dialUpNetwork',
  'error',
  'msgError0',
  'gameFreecell2',
  'gameSpider0',
  'helpFile',
  'explorer',
  'folderOpen',
  'folderClosed',
  'fallback',
  'fonts',
  'help',
  'internet',
  'leaderboard',
  'menuArrow',
  'midiFile',
  'minesweeper',
  'mailEnvelope',
  'envelopeClosed0',
  'mailEnvelopeOpen',
  'earthRating',
  'mailFolderClosed',
  'mailFolderOpen',
  'mailSent',
  'mailSpam',
  'mailToolDelete',
  'mailToolForward',
  'mailToolNew',
  'mailToolReply',
  'mailToolSend',
  'mailTrashEmpty',
  'microsoftMoney99',
  'networkNeighborhood',
  'netVoiceHandset',
  'notepad',
  'notepadDoc',
  'passwordVault',
  'power',
  'printers',
  'program',
  'programs',
  'quickView',
  'question',
  'restrict1',
  'shutdown',
  'smiley',
  'sound',
  'soundOff',
  'system',
  'trust00',
  'videoFile',
  'warning',
  'waveFile',
  'windowsLogo',
  'webFileSet0',
  'winRar3',
  'lotusWordPro97',
  'wordpadDoc',
] as const;

export type IconId = typeof iconIds[number];

export const iconSizes = [8, 16, 24, 32] as const;

export type IconSize = typeof iconSizes[number];

export type IconUrls = Partial<{ [key in IconSize]: string }>;

export type IconList = { [key in IconId]: IconUrls };
